language: java
jdk:
  - oraclejdk8
node_js: "1.4.14"

before_script:
  - ". $HOME/.nvm/nvm.sh"
  - "nvm install stable"
  - "nvm use stable"
  - "mvn clean"

install:
  - "mvn clean"
  - "cd src/main/resources/static/"
  - "npm run test-single-run"