language: java
jdk:
  - oraclejdk8
node_js: "v6.1.0"

#before_install:
#  - ". $HOME/.nvm/nvm.sh"
#  - "nvm install stable"
#  - "nvm use stable"
#  - "npm install"

install:
  - "mvn clean compile"
  - "cd src/main/resources/static/"
  - "npm install"
  - "cd ../../../.."
script:
  - "mvn test"
  - "cd src/main/resources/static/"
  - "npm run test-single-run"