language: java
jdk:
  - oraclejdk8
node_js: "1.4.14"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - "cd src/main/resources/static/"
  - "npm install"
script: "npm test"