language: java
jdk:
  - oraclejdk8
node_js: "1.4.14"

before_install:
  - ". $HOME/.nvm/nvm.sh"
  - "nvm install stable"
  - "nvm use stable"
  - "mvn clean"
  - "npm install"

install:
  - "mvn install"
  - "cd src/main/resources/static/"
  - "npm run test-single-run"